
  name: v4l2camera
  version: git
  summary: Web interface to V4L2
  description: |
    This is a Web interface to V4L2, the http server use civetweb. 

  grade: stable 
  confinement: strict
  base: core22

  parts:
    ui:
      plugin: npm
      source: vuejs  
  
    v4l2web:
      plugin: make
      source: .
      source-type: git
      build-packages:
      - g++
      - make
      - cmake
      - pkg-config
      - libjpeg-dev
      - libssl-dev
      - npm
      stage-packages:
      - libjpeg8
      - libssl3

  apps:
    v4l2web:
      command: bin/v4l2web -P $SNAP/share/v4l2web/webroot
      daemon: simple   
      plugs: [network-bind]
