
  name: v4l2web
  version: git
  summary: Web interface to V4L2
  description: |
    This is a Web interface to V4L2, the http server use civetweb. 

  grade: stable 
  confinement: strict
  base: core20

  parts:
    v4l2web:
      plugin: make
      source: .
      source-type: git
      build-packages:
      - g++
      - make
      - cmake
      - pkg-config
      - libjsoncpp-dev
      - libjpeg-dev
      - libssl-dev
      - npm
      stage-packages:
      - libjsoncpp1 
      - libjpeg8
      - libssl1.1

  apps:
    v4l2web:
      command: bin/v4l2web -P $SNAP/share/v4l2web/webroot
      daemon: simple   
      plugs: [network-bind]
