name: Node.js Package

on: [push]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
              git submodule update --init
              git fetch --prune --unshallow --tags
              
      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://npm.pkg.github.com'
          always-auth: true
          
      - run: |
              cd vuejs
              npm install
              npm config set git-tag-version=false
              npm config ls -l
              cat $(npm config get userconfig)              
              npm version $(git describe --tags --always)
          
      - run: cd vuejs && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              
      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://registry.npmjs.org'
          always-auth: true
          
      - run: cd vuejs && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
